In [0]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed(100)

In [0]:
(x_img_train,y_label_train), \
(x_img_test, y_label_test)=cifar100.load_data()

In [34]:
print('train:',len(x_img_train))
print('test :',len(x_img_test))

train: 50000
test : 10000


In [35]:
# 查詢檔案維度資訊
x_img_train.shape

(50000, 32, 32, 3)

In [36]:
# 查詢檔案維度資訊
y_label_train.shape

(50000, 1)

In [37]:
# 查詢檔案維度資訊
x_img_test.shape

(10000, 32, 32, 3)

In [38]:
# 查詢檔案維度資訊
y_label_test.shape

(10000, 1)

In [39]:
print('x_img_test:',x_img_test.shape)
print('y_label_test :',y_label_test.shape)

x_img_test: (10000, 32, 32, 3)
y_label_test : (10000, 1)


In [40]:
x_img_train[0][0][0]

array([255, 255, 255], dtype=uint8)

In [0]:
x_img_train_normalize = x_img_train.astype('float32') / 255.0
x_img_test_normalize = x_img_test.astype('float32') / 255.0

In [42]:
x_img_train_normalize[0][0][0]

array([1., 1., 1.], dtype=float32)

In [43]:
y_label_train.shape

(50000, 1)

In [44]:
y_label_train[:5]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1]])

In [0]:
from keras.utils import np_utils
y_label_train_OneHot = np_utils.to_categorical(y_label_train)
y_label_test_OneHot = np_utils.to_categorical(y_label_test)